name: Develop
on:
  push:
    branches:
      - "develop"
      - "feature/*"
      - "release/*"
      - "hotfix/*"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        id: checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        id: install
        run: yarn install

      - name: Lint
        id: lint
        run: yarn lint

  tag-prerelease:
    name: Tag pre-release
    needs: test
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        id: checkout
        uses: actions/checkout@v3

      - name: Get latest version
        id: get-latest-version
        uses: actions-ecosystem/action-get-latest-tag@v1
        with:
          semver_only: true
          with_initial_version: true

      - name: Create version tag
        id: create-version-tag
        run: |
          echo 'version=${{ steps.get-latest-version.outputs.tag }}_snapshot_${{ github.run_number }}' >> $GITHUB_OUTPUT

      - name: Set snapshot tag
        id: set-snapshot-tag
        uses: rickstaa/action-create-tag@v1
        with:
          tag: ${{ steps.create-version-tag.outputs.version }}

  create-prerelease:
    name: Create pre-release
    needs: tag-prerelease
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        id: checkout
        uses: actions/checkout@v3

      - name: Get version
        id: get-version
        run: echo 'version=${GITHUB_REF#refs/*/}' >> $GITHUB_OUTPUT

      - name: Zip release
        run: zip -r ${{ steps.get-version.outputs.version }}.zip ./tracking-templates/*

      - name: Create release
        id: create-release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ steps.get-version.outputs.version }}
          files: ${{ steps.get-version.outputs.version }}.zip
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
