name: Build, test and release
on:
  push:
    branches:
      - "!develop"
    tags:
      - "v*.*.*"

jobs:
  test-and-release:
    name: Test and release
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        id: checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        id: install
        run: yarn install

      - name: Lint
        id: lint
        run: yarn lint

      - name: Get version
        id: get-version
        run: echo 'version=${GITHUB_REF#refs/*/}' >> $GITHUB_OUTPUT

      - name: Zip release
        run: zip -r ${{ steps.get-version.outputs.version }}.zip ./tracking-templates/*

      - name: Create release
        id: create-release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ steps.get-version.outputs.version }}
          files: ${{ steps.get-version.outputs.version }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
