name: Release
on:
  push:
    branches:
      - "!develop"
    tags:
      - "v*.*.*"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        id: checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        id: install
        run: yarn install

      - name: Lint
        id: lint
        run: yarn lint

      - name: Test app
        id: test
        run: npm run ci

  release:
    name: Release
    needs: test
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        id: checkout
        uses: actions/checkout@v3

      - name: Get version
        id: get-version
        run: echo 'version=${GITHUB_REF#refs/*/}' >> $GITHUB_OUTPUT

      - name: Zip release
        run: zip -r ${{ steps.get-version.outputs.version }}.zip ./tracking-templates/*

      - name: Create release
        id: create-release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ steps.get-version.outputs.version }}
          files: ${{ steps.get-version.outputs.version }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
